version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://sheldor:Sheldon0@192.168.178.19:27778/meal-planner

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9988:80"
    depends_on:
      - backend