version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://sheldor:Sheldon0@192.168.178.19:27778/meal-planner
      - CORS_ORIGIN=http://192.168.178.19:9988,http://localhost,http://localhost:5173

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9988:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3000